### ISSUE TITLE
Create, please, list for 2022

### ISSUE THREAD

**Issue by MrHakimov** [pittcsc/NewGrad-2021#162]

**Comment by Zmwang622** [comment]
@gintass Shall we?

**Comment by ShrutiMavani** [comment]
Will you create a different link or keep the same link for 2022?

**Comment by Siyangyang** [comment]
Please have a 2022 new grad list

**Comment by stevencheng1220** [comment]
Would be great to be on the look out for 2022 full time positions!

**Comment by monishshah18** [comment]
Yes, Amazon has posted full time SDE Roles for 2022( graduating between Feb 2022-October 2022).

**Comment by bryanhitc** [comment]
Looks like someone forked this repo with a 2022 version: https://github.com/coderQuad/New-Grad-Positions-2022

I'm not sure how well it'll be maintained, but it may be worth tracking. Good luck! :)
